### ISSUE TITLE
【BUG】升级Masa.Blazor至最新版本后NavigationManager.RegisterLocationChangingHandler问题

### ISSUE THREAD

**Issue by Memoyu** [masastack/Masa.Blazor.MauiDemo#4]
#### 描述：
将Masa.Blazor升级至最新1.7.8后，打开Todo页面会触发NavigationManager.RegisterLocationChangingHandler，后再到User页面跳转页面，再返回时出现页面跳转未按预先路径回退
![masa-bug](https://github.com/user-attachments/assets/f3181781-1220-4448-aabb-13002eb62fee)

#### 复现：
1. 升级Masa.Blazor 至 1.7.8
2. 启动项目后先点击Todo页面
3. 再到User页面，再进行页面跳转：设置 -> Dark-mode或About us 
4. 点击顶部导航栏返回

**Comment by capdiem** [comment]
Please check masastack/Masa.Blazor#2211
